name: Yuichi Shiraishi
degree: Ph.D.
description: Assistant Professor</br>Laboratory of DNA Information Analysis, Human Genome Center, The Institute of Medical Science, The University of Tokyo</br>friend1ws [at] gmail [dot] com
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
