title: Yuichi Shiraishi, Ph.D.
description: Unit Leader</br>National Cancer Center Research Institute</br>friend1ws [at] gmail [dot] com
show_downloads: true
google_analytics: UA-110011805-1
theme: jekyll-theme-minimal
wordpress_url: http://friend1ws.net/blog/
