title: Yuichi Shiraishi, Ph.D.
description: Assistant Professor</br>Laboratory of DNA Information Analysis, Human Genome Center, The Institute of Medical Science, The University of Tokyo</br>friend1ws [at] gmail [dot] com
show_downloads: true
google_analytics: UA-110011805-1
theme: jekyll-theme-minimal
wordpress_url: http://friend1ws.net/blog/
